apiVersion: v1
kind: Service
metadata:
  name: scoring
  labels:
    app.kubernetes.io/name: scoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scoring
  ports:
    - name: http
      port: 8033
      targetPort: http
