apiVersion: v1
kind: Service
metadata:
  name: structuring
  labels:
    app.kubernetes.io/name: structuring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: structuring
  ports:
    - name: http
      port: 8032
      targetPort: http
