apiVersion: v1
kind: Service
metadata:
  name: guardrails # nama ini adalah alamatnya: http://guardrails:8031 di dalam namespace
  labels:
    app.kubernetes.io/name: guardrails
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: guardrails
  ports:
    - name: http
      port: 8031
      targetPort: http
