"""
API (presentation) layer untuk kontrak OCR yang dipanggil ocr-orchestration.
Parsing HTTP, panggil service, ServiceError -> HTTPException. Tidak ada
aturan bisnis di sini; lihat src/services/ocr_service.py.
"""

from fastapi import APIRouter, Depends, Form, HTTPException, UploadFile

from src.api.v1.ekstraksi import get_ekstraksi_service
from src.api.v1.guardrails import get_guardrails_service
from src.api.v1.intake import FileField, FileUrlField, read_image
from src.api.v1.scoring import get_scoring_service
from src.api.v1.structuring import get_structuring_service
from src.core.config import get_settings
from src.core.envelope import envelope
from src.core.errors import ServiceError
from src.core.security import API_KEY_ERROR, verify_api_key
from src.repositories.request_repository import get_request_repository
from src.schemas.errors import error
from src.schemas.ocr import RID, ExtractOcrResponse, GenerateRequestIdResponse, GetOcrResultResponse
from src.services.ocr_service import OcrService

router = APIRouter(tags=["NPWP OCR"], dependencies=[Depends(verify_api_key)])


def get_ocr_service() -> OcrService:
    return OcrService(
        get_request_repository(),
        get_guardrails_service(),
        get_ekstraksi_service(),
        get_structuring_service(),
        get_scoring_service(),
    )


@router.post(
    "/v1/generate-request-id",
    response_model=GenerateRequestIdResponse,
    summary="Generate a request_id",
    description="Mints a request_id that must be used in a subsequent call to /v1/extract-ocr.",
    responses={401: error(401, "Missing or invalid X-API-Key", API_KEY_ERROR)},
)
async def generate_request_id(service: OcrService = Depends(get_ocr_service)):
    request_id = await service.generate_request_id()
    return envelope(200, "Success", {"request_id": request_id}, request_id)


@router.post(
    "/v1/extract-ocr",
    response_model=ExtractOcrResponse,
    summary="Extract data from an NPWP image",
    description=(
        "Runs the full pipeline (guardrails -> ekstraksi -> structuring -> scoring) on the "
        "uploaded NPWP image for the given request_id (from /v1/generate-request-id). "
        "A request_id can only be submitted once.\n\n"
        "Send the image as `file`, or send `file_url` and this service fetches "
        "it itself; exactly one of the two."
    ),
    responses={
        400: error(
            400, "Unknown request_id, bad file, or low image quality", "Uploaded image is not recognized as an NPWP"
        ),
        401: error(401, "Missing or invalid X-API-Key", API_KEY_ERROR),
        409: error(409, "request_id was already processed", f"request_id {RID} has already been processed"),
        500: error(500, "OCR engine failed", "Internal server error while processing OCR"),
        422: error(422, "Validation Error", "body.request_id: Field required", errors="VALIDATION_ERROR"),
    },
)
async def extract_ocr(
    request_id: str = Form(..., description="request_id from /v1/generate-request-id"),
    file: UploadFile | str | None = FileField,
    file_url: str | None = FileUrlField,
    service: OcrService = Depends(get_ocr_service),
):
    content, filename, content_type = await read_image(file, file_url, limit=get_settings().max_upload_bytes)
    try:
        data, guardrails = await service.extract(request_id, filename, content_type, content)
    except ServiceError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)
    return envelope(200, "Success", data, request_id, guardrails=guardrails)


@router.get(
    "/v1/get-ocr-result/{request_id}",
    response_model=GetOcrResultResponse,
    summary="Get OCR result / status",
    description="Fetches the current status and (if completed) the result for a previously generated request_id.",
    responses={
        401: error(401, "Missing or invalid X-API-Key", API_KEY_ERROR, request_id=RID),
        404: error(
            404,
            "request_id was never generated by this service",
            f"No data found for request_id: {RID}",
            request_id=RID,
        ),
        422: error(
            422, "Validation Error", "path.request_id: Field required", request_id=RID, errors="VALIDATION_ERROR"
        ),
    },
)
async def get_ocr_result(request_id: str, service: OcrService = Depends(get_ocr_service)):
    try:
        data = await service.get_result(request_id)
    except ServiceError as exc:
        raise HTTPException(status_code=exc.status_code, detail=exc.message)
    # Skor dokumen naik ke envelope, sejajar dengan jalur extract-ocr. Kalau
    # ditinggal di dalam `data`, dua endpoint yang sama isinya jadi beda bentuk.
    return envelope(200, "Success", data, request_id, guardrails=data.pop("guardrails", None))
